### ISSUE TITLE
macOS icon in dash don't open the app again.

### ISSUE THREAD

**Issue by manuelernestog** [manuelernestog/weektodo-web#143]
The problem was reported by two macOS users. When you close the app, and you try to open it from the dash it does not show the app. You have to go to the Tray icon and open it from there.

**Comment by merodriguez9112** [comment]
In version 1.8.1 I made some changes in order to solve this, unfortunately I don't have any PC with macOS to test it, so I made the change blindly, if any user sees this and can give me some feedback on whether the error persists or solved it would be helpful. Thanks.

**Comment by manuelernestog** [comment]
Finally fixed on version 1.9
