### ISSUE TITLE
Add a "Share or Copy" button for each list.

### ISSUE THREAD

**Issue by IT-Tool** [manuelernestog/weektodo-web#2]
For example, to be able to copy the entire plan for the day to send this list to someone.
Or insert it into a program for qr codes (like QtQR) and scan it with a smartphone. To have a plan at hand.

**Comment by cocoonkid** [comment]
+1

**Comment by manuelernestog** [comment]
Sorry about the delay of this feature :smiling_face_with_tear: , this was finally added on version 1.9.0. Closing this issue.
